### ISSUE TITLE
Join our project ?

### ISSUE THREAD

**Issue by ghost** [Hmerritt/discord-encryption#2]
Hi there, it seems you've taken the same interest as we ( as a group ), have.

If possible, we'd like you to join our team as we could use someone with the same ambitions as us to implement a general encryption plugin for Discord.

If you'd like to see our work so far, check it out here: http://gitlab.com/leogx9r/DiscordCrypt

( We don't use GitHub due to their highly restrictive abilities and infringement on user privacy. )

If you'd like to contact us, please join our Discord server. ( https://discord.gg/3uakNmM )

![Here's an example of our plugin's encryption](https://gitlab.com/leogx9r/DiscordCrypt/raw/master/images/encrypted-message.png)

**Comment by leogatesx9r** [comment]
I'd also like to point out that this plugin, rather than relying on external sources, uses Discord's native encryption capabilities to implement multiple levels of encryption and also has the ability to manually enable or disable encryption or features.

Please don't take this as a form of advertising, we're actually quite interested in you as a potential partner. :)

**Comment by Bluscream** [comment]
Were you inspired by my https://r4p3.net/threads/betterdiscord-encrypted-text.2008/ ?
